import Image from "next/image";
import Link from "next/link";
import { bookingUrl, gallery } from "@/data/site";
import { SectionHeading } from "@/components/SectionHeading";
import { ServiceList } from "@/components/ServiceList";
import { GoogleReviews } from "@/components/GoogleReviews";

export default function Home() { return <>
  <section className="hero"><div className="hero-slideshow" aria-hidden="true">{["IMG_2950.jpeg","IMG_2947.jpeg","IMG_3188.jpeg","IMG_2931.jpeg"].map((src,i)=><div className="hero-slide" key={src}><Image className="hero-backdrop" src={`/images/${src}`} alt="" fill priority={i===0} sizes="100vw"/><Image className="hero-photo" src={`/images/${src}`} alt="" fill priority={i===0} sizes="100vw"/></div>)}</div><div className="hero-shade"/><div className="hero-copy"><p className="hero-brand">Starz Barber &amp; Beauty</p><p className="hero-location">Horn Lake, Mississippi · Since 2008</p><p className="lede">Family-friendly barber and beauty services at 1731 Dancy Boulevard.</p><div className="actions"><a className="button" href={bookingUrl}>Book Appointment</a><Link className="text-link light" href="/services">Services &amp; prices →</Link></div><div className="proof"><span><strong>4.9 ★</strong> rating on Google</span></div></div><span className="scroll-cue" aria-hidden="true">Scroll <i/></span></section>
  <section className="section wrap"><SectionHeading title="Popular appointments" copy="See prices and appointment times before you book."/><ServiceList limit={6}/><Link className="button button-outline" href="/services">See all services</Link></section>
  <section className="split dark"><div className="split-image"><Image src="/images/IMG_2950.jpeg" alt="Precise razor work during a haircut at Starz" fill sizes="(max-width: 800px) 100vw, 50vw"/></div><div className="split-copy"><h2>We take the time to get the cut right.</h2><p>We pay attention to your hairline, growth pattern and how you want to wear your cut. Tell us what you’re looking for, and we’ll handle the details.</p><Link className="text-link light" href="/about">Meet Starz →</Link></div></section>
  <section className="section wrap"><SectionHeading title="Recent cuts and styles"/><div className="gallery-preview">{gallery.slice(0,6).map((g,i)=><div className={`gallery-tile tile-${i}`} key={g.src}><Image src={g.src} alt={g.alt} fill sizes="(max-width: 600px) 50vw, 33vw"/></div>)}</div><Link className="button button-outline" href="/gallery">See more work</Link></section>
  <GoogleReviews/>
  <section className="family wrap"><div><h2>Horn Lake has trusted Starz since 2008.</h2><p>Starz is the kind of neighborhood shop where people settle into the chair, catch up and leave looking sharp. Some clients have been coming for years; others are walking in for the first time. Every appointment gets the same attention to detail.</p><p>Wi-Fi is available while you wait or while family members are in the chair.</p></div><Image src="/images/IMG_3188.jpeg" alt="Waiting area inside Starz Barber and Beauty" width={900} height={1200}/></section>
  <section className="visit-cta enhanced"><p className="visit-kicker">1731 Dancy Boulevard · Horn Lake</p><h2>Make time for your next cut.</h2><p>Choose your service, select an available time and come see us at Starz.</p><div className="actions"><a className="button" href={bookingUrl}>Book Appointment</a><a className="button button-outline" href="tel:+19014068988">Call (901) 406-8988</a></div></section>
  </>; }

