import Image from "next/image";
import Link from "next/link";
import { bookingUrl, gallery } from "@/data/site";
import { SectionHeading } from "@/components/SectionHeading";
import { ServiceList } from "@/components/ServiceList";

export default function Home() { return <>
  {/* Hero */}<section className="hero"><div className="hero-copy"><p className="eyebrow">BARBER &amp; BEAUTY IN HORN LAKE</p><h1>Barbering for the whole family, right here in Horn Lake</h1><p className="lede">From adult and youth cuts to beard work, color and natural styles, Starz has served North Mississippi since 2008.</p><div className="actions"><a className="button" href={bookingUrl}>Book an appointment</a><Link className="text-link" href="/services">View services →</Link></div><div className="proof"><span><strong>5.0</strong> on Booksy</span><span>Child-friendly</span><span>Parking on site</span></div></div><div className="hero-image"><Image src="/images/IMG_2947.jpeg" alt="J. Wise shaping a client's beard at Starz" fill priority sizes="(max-width: 800px) 100vw, 48vw"/></div></section>
  {/* Popular services */}<section className="section wrap"><SectionHeading eyebrow="IN THE CHAIR" title="The appointments our regulars keep coming back for" copy="Straightforward timing and pricing, so you know what to book before you arrive."/><ServiceList limit={6}/><Link className="button button-outline" href="/services">See the full menu</Link></section>
  {/* Craft */}<section className="split dark"><div className="split-image"><Image src="/images/IMG_2950.jpeg" alt="Precise razor work during a haircut at Starz" fill sizes="(max-width: 800px) 100vw, 50vw"/></div><div className="split-copy"><p className="eyebrow">THE WORK</p><h2>A sharp finish starts with paying attention</h2><p>Hairline, growth pattern, beard shape and how you wear it on an ordinary Tuesday — those details matter here. We take the time to make the cut fit the person in the chair.</p><Link className="text-link light" href="/about">Meet Starz →</Link></div></section>
  {/* Gallery */}<section className="section wrap"><SectionHeading eyebrow="RECENT WORK" title="Finished in the Starz chairs"/><div className="gallery-preview">{gallery.slice(0,6).map((g,i)=><div className={`gallery-tile tile-${i}`} key={g.src}><Image src={g.src} alt={g.alt} fill sizes="(max-width: 600px) 50vw, 33vw"/></div>)}</div><Link className="button button-outline" href="/gallery">Open the gallery</Link></section>
  {/* Family */}<section className="family wrap"><div><p className="eyebrow">SINCE 2008</p><h2>A neighborhood shop that makes room for everybody</h2><p>Parents bring the kids. Longtime clients come back for the same careful line-up. New clients can ask questions without feeling rushed. Starz is built around the kind of appointments people can settle into.</p><div className="amenities"><span>Accessible entrance</span><span>Cards accepted</span><span>Wi-Fi available</span></div></div><Image src="/images/IMG_3188.jpeg" alt="Family-friendly waiting area inside Starz" width={900} height={1200}/></section>
  {/* Visit CTA */}<section className="visit-cta"><p className="eyebrow">1731 DANCY BLVD · HORN LAKE</p><h2>Your next chair is ready</h2><p>Pick the service that fits, choose an available time and we’ll see you at the shop.</p><a className="button" href={bookingUrl}>Find an appointment</a></section>
  </>; }
