import Image from "next/image";
import Link from "next/link";
import { bookingUrl, gallery } from "@/data/site";
import { SectionHeading } from "@/components/SectionHeading";
import { ServiceList } from "@/components/ServiceList";
import { GoogleReviews } from "@/components/GoogleReviews";

export default function Home() { return <>
  <section className="hero"><div className="hero-slideshow" aria-hidden="true">{["IMG_2950.jpeg","IMG_2947.jpeg","IMG_3188.jpeg","IMG_2931.jpeg"].map((src,i)=><div className="hero-slide" key={src}><Image className="hero-backdrop" src={`/images/${src}`} alt="" fill priority={i===0} sizes="100vw"/><Image className="hero-photo" src={`/images/${src}`} alt="" fill priority={i===0} sizes="100vw"/></div>)}</div><div className="hero-shade"/><div className="hero-copy"><p className="hero-brand">Starz Barber &amp; Beauty</p><p className="hero-location">Horn Lake, Mississippi · Since 2008</p><p className="lede">Family-friendly barber and beauty services at 1731 Dancy Boulevard.</p><div className="actions"><a className="button" href={bookingUrl}>Book Appointment</a><Link className="text-link light" href="/services">Services &amp; prices →</Link></div><div className="proof"><span><strong>4.9 ★</strong> rating on Google</span></div></div></section>
  <section className="section wrap"><SectionHeading title="Popular appointments" copy="See prices and appointment times before you book."/><ServiceList limit={6}/><Link className="button button-outline" href="/services">See all services</Link></section>
  <section className="split dark"><div className="split-image"><Image src="/images/IMG_2950.jpeg" alt="Barber working with a client at Starz" fill sizes="(max-width: 800px) 100vw, 50vw"/></div><div className="split-copy"><h2>Meet the Starz staff</h2><p>Get to know J. Wise and the people behind the barbering, beard care, color and natural-hair services offered at Starz.</p><Link className="text-link light" href="/about">Meet the team →</Link></div></section>
  <section className="section wrap"><SectionHeading title="Recent cuts and styles"/><div className="gallery-preview">{[0,2,5,8,11,14].map((index)=><div className="gallery-tile" key={gallery[index].src}><Image src={gallery[index].src} alt={gallery[index].alt} fill sizes="(max-width: 600px) 50vw, 33vw"/></div>)}</div><Link className="button button-outline" href="/gallery">See more work</Link></section>
  <GoogleReviews/>
  <section className="family wrap"><div><h2>Horn Lake has trusted Starz since 2008.</h2><p>Starz has grown through years of repeat appointments, family referrals and conversations across the chair. Longtime clients know the shop; first-time clients get the same welcome and careful attention.</p><p>Come in for the service you booked, stay comfortable while you wait and use the available Wi-Fi if you need it.</p></div><div className="family-media"><Image className="family-photo" src="/images/IMG_3188.jpeg" alt="Waiting area inside Starz Barber and Beauty" fill sizes="(max-width:800px) 100vw,45vw"/></div></section>
  <section className="visit-cta enhanced"><div><p className="visit-kicker">1731 Dancy Boulevard · Horn Lake</p><h2>Appointments</h2><p>View available services and times, or call the shop if you have a question before booking.</p></div><div className="actions"><a className="button" href={bookingUrl}>Book Appointment</a><a className="button button-outline" href="tel:+19014068988">Call (901) 406-8988</a></div></section>
  </>; }

